// Pixel Rumble game roster.
// Fields: id (unique slug), title, year, genre, platform (original/most-associated), dev.
// One entry per game; remakes and expansions are deliberately left out.
window.GAMES = [
  // 1970s–1980s
  { id: "pong", title: "Pong", year: 1972, genre: "Arcade", platform: "Arcade", dev: "Atari" },
  { id: "space-invaders", title: "Space Invaders", year: 1978, genre: "Arcade", platform: "Arcade", dev: "Taito" },
  { id: "pac-man", title: "Pac-Man", year: 1980, genre: "Arcade", platform: "Arcade", dev: "Namco" },
  { id: "donkey-kong", title: "Donkey Kong", year: 1981, genre: "Arcade", platform: "Arcade", dev: "Nintendo" },
  { id: "galaga", title: "Galaga", year: 1981, genre: "Arcade", platform: "Arcade", dev: "Namco" },
  { id: "frogger", title: "Frogger", year: 1981, genre: "Arcade", platform: "Arcade", dev: "Konami" },
  { id: "dig-dug", title: "Dig Dug", year: 1982, genre: "Arcade", platform: "Arcade", dev: "Namco" },
  { id: "tetris", title: "Tetris", year: 1984, genre: "Puzzle", platform: "Multi", dev: "Alexey Pajitnov" },
  { id: "super-mario-bros", title: "Super Mario Bros.", year: 1985, genre: "Platformer", platform: "NES", dev: "Nintendo" },
  { id: "the-legend-of-zelda", title: "The Legend of Zelda", year: 1986, genre: "Action-Adventure", platform: "NES", dev: "Nintendo" },
  { id: "metroid", title: "Metroid", year: 1986, genre: "Action-Adventure", platform: "NES", dev: "Nintendo" },
  { id: "castlevania", title: "Castlevania", year: 1986, genre: "Action", platform: "NES", dev: "Konami" },
  { id: "out-run", title: "Out Run", year: 1986, genre: "Racing", platform: "Arcade", dev: "Sega" },
  { id: "mega-man", title: "Mega Man", year: 1987, genre: "Platformer", platform: "NES", dev: "Capcom" },
  { id: "contra", title: "Contra", year: 1987, genre: "Shooter", platform: "NES", dev: "Konami" },
  { id: "metal-gear", title: "Metal Gear", year: 1987, genre: "Action", platform: "NES", dev: "Konami" },
  { id: "punch-out", title: "Punch-Out!!", year: 1987, genre: "Sports", platform: "NES", dev: "Nintendo" },
  { id: "mega-man-2", title: "Mega Man 2", year: 1988, genre: "Platformer", platform: "NES", dev: "Capcom" },
  { id: "simcity", title: "SimCity", year: 1989, genre: "Simulation", platform: "PC", dev: "Maxis" },
  { id: "prince-of-persia", title: "Prince of Persia", year: 1989, genre: "Platformer", platform: "PC", dev: "Broderbund" },

  // 1990s
  { id: "super-mario-bros-3", title: "Super Mario Bros. 3", year: 1990, genre: "Platformer", platform: "NES", dev: "Nintendo" },
  { id: "monkey-island", title: "The Secret of Monkey Island", year: 1990, genre: "Adventure", platform: "PC", dev: "Lucasfilm Games" },
  { id: "sonic-the-hedgehog", title: "Sonic the Hedgehog", year: 1991, genre: "Platformer", platform: "Genesis", dev: "Sega" },
  { id: "street-fighter-ii", title: "Street Fighter II", year: 1991, genre: "Fighting", platform: "Arcade", dev: "Capcom" },
  { id: "super-mario-world", title: "Super Mario World", year: 1991, genre: "Platformer", platform: "SNES", dev: "Nintendo" },
  { id: "zelda-link-to-the-past", title: "The Legend of Zelda: A Link to the Past", year: 1991, genre: "Action-Adventure", platform: "SNES", dev: "Nintendo" },
  { id: "mortal-kombat", title: "Mortal Kombat", year: 1992, genre: "Fighting", platform: "Arcade", dev: "Midway" },
  { id: "wolfenstein-3d", title: "Wolfenstein 3D", year: 1992, genre: "Shooter", platform: "PC", dev: "id Software" },
  { id: "doom", title: "DOOM", year: 1993, genre: "Shooter", platform: "PC", dev: "id Software" },
  { id: "nba-jam", title: "NBA Jam", year: 1993, genre: "Sports", platform: "Arcade", dev: "Midway" },
  { id: "super-metroid", title: "Super Metroid", year: 1994, genre: "Action-Adventure", platform: "SNES", dev: "Nintendo" },
  { id: "final-fantasy-vi", title: "Final Fantasy VI", year: 1994, genre: "RPG", platform: "SNES", dev: "Square" },
  { id: "donkey-kong-country", title: "Donkey Kong Country", year: 1994, genre: "Platformer", platform: "SNES", dev: "Rare" },
  { id: "earthbound", title: "EarthBound", year: 1994, genre: "RPG", platform: "SNES", dev: "HAL Laboratory" },
  { id: "chrono-trigger", title: "Chrono Trigger", year: 1995, genre: "RPG", platform: "SNES", dev: "Square" },
  { id: "super-mario-64", title: "Super Mario 64", year: 1996, genre: "Platformer", platform: "N64", dev: "Nintendo" },
  { id: "pokemon-red-blue", title: "Pokémon Red and Blue", year: 1996, genre: "RPG", platform: "GB", dev: "Game Freak" },
  { id: "mario-kart-64", title: "Mario Kart 64", year: 1996, genre: "Racing", platform: "N64", dev: "Nintendo" },
  { id: "final-fantasy-vii", title: "Final Fantasy VII", year: 1997, genre: "RPG", platform: "PS1", dev: "Square" },
  { id: "goldeneye-007", title: "GoldenEye 007", year: 1997, genre: "Shooter", platform: "N64", dev: "Rare" },
  { id: "gran-turismo", title: "Gran Turismo", year: 1997, genre: "Racing", platform: "PS1", dev: "Polyphony Digital" },
  { id: "starcraft", title: "StarCraft", year: 1998, genre: "Strategy", platform: "PC", dev: "Blizzard" },
  { id: "zelda-ocarina-of-time", title: "The Legend of Zelda: Ocarina of Time", year: 1998, genre: "Action-Adventure", platform: "N64", dev: "Nintendo" },
  { id: "half-life", title: "Half-Life", year: 1998, genre: "Shooter", platform: "PC", dev: "Valve" },
  { id: "metal-gear-solid", title: "Metal Gear Solid", year: 1998, genre: "Action", platform: "PS1", dev: "Konami" },
  { id: "resident-evil-2", title: "Resident Evil 2", year: 1998, genre: "Horror", platform: "PS1", dev: "Capcom" },
  { id: "tekken-3", title: "Tekken 3", year: 1998, genre: "Fighting", platform: "PS1", dev: "Namco" },
  { id: "pokemon-gold-silver", title: "Pokémon Gold and Silver", year: 1999, genre: "RPG", platform: "GB", dev: "Game Freak" },
  { id: "silent-hill", title: "Silent Hill", year: 1999, genre: "Horror", platform: "PS1", dev: "Konami" },
  { id: "soulcalibur", title: "Soulcalibur", year: 1999, genre: "Fighting", platform: "Dreamcast", dev: "Namco" },
  { id: "shenmue", title: "Shenmue", year: 1999, genre: "Action-Adventure", platform: "Dreamcast", dev: "Sega" },
  { id: "age-of-empires-ii", title: "Age of Empires II", year: 1999, genre: "Strategy", platform: "PC", dev: "Ensemble Studios" },

  // 2000s
  { id: "tony-hawk-2", title: "Tony Hawk's Pro Skater 2", year: 2000, genre: "Sports", platform: "PS1", dev: "Neversoft" },
  { id: "the-sims", title: "The Sims", year: 2000, genre: "Simulation", platform: "PC", dev: "Maxis" },
  { id: "counter-strike", title: "Counter-Strike", year: 2000, genre: "Shooter", platform: "PC", dev: "Valve" },
  { id: "diablo-ii", title: "Diablo II", year: 2000, genre: "RPG", platform: "PC", dev: "Blizzard" },
  { id: "deus-ex", title: "Deus Ex", year: 2000, genre: "Action", platform: "PC", dev: "Ion Storm" },
  { id: "zelda-majoras-mask", title: "The Legend of Zelda: Majora's Mask", year: 2000, genre: "Action-Adventure", platform: "N64", dev: "Nintendo" },
  { id: "gta-iii", title: "Grand Theft Auto III", year: 2001, genre: "Action", platform: "PS2", dev: "Rockstar North" },
  { id: "halo-combat-evolved", title: "Halo: Combat Evolved", year: 2001, genre: "Shooter", platform: "Xbox", dev: "Bungie" },
  { id: "super-smash-bros-melee", title: "Super Smash Bros. Melee", year: 2001, genre: "Fighting", platform: "GC", dev: "Nintendo" },
  { id: "ico", title: "Ico", year: 2001, genre: "Action-Adventure", platform: "PS2", dev: "Team Ico" },
  { id: "silent-hill-2", title: "Silent Hill 2", year: 2001, genre: "Horror", platform: "PS2", dev: "Konami" },
  { id: "final-fantasy-x", title: "Final Fantasy X", year: 2001, genre: "RPG", platform: "PS2", dev: "Square" },
  { id: "devil-may-cry", title: "Devil May Cry", year: 2001, genre: "Action", platform: "PS2", dev: "Capcom" },
  { id: "metroid-prime", title: "Metroid Prime", year: 2002, genre: "Action-Adventure", platform: "GC", dev: "Retro Studios" },
  { id: "animal-crossing", title: "Animal Crossing", year: 2002, genre: "Simulation", platform: "GC", dev: "Nintendo" },
  { id: "kotor", title: "Star Wars: Knights of the Old Republic", year: 2003, genre: "RPG", platform: "Xbox", dev: "BioWare" },
  { id: "prince-of-persia-sands-of-time", title: "Prince of Persia: The Sands of Time", year: 2003, genre: "Action-Adventure", platform: "PS2", dev: "Ubisoft" },
  { id: "katamari-damacy", title: "Katamari Damacy", year: 2004, genre: "Puzzle", platform: "PS2", dev: "Namco" },
  { id: "gta-san-andreas", title: "Grand Theft Auto: San Andreas", year: 2004, genre: "Action", platform: "PS2", dev: "Rockstar North" },
  { id: "half-life-2", title: "Half-Life 2", year: 2004, genre: "Shooter", platform: "PC", dev: "Valve" },
  { id: "world-of-warcraft", title: "World of Warcraft", year: 2004, genre: "RPG", platform: "PC", dev: "Blizzard" },
  { id: "resident-evil-4", title: "Resident Evil 4", year: 2005, genre: "Horror", platform: "GC", dev: "Capcom" },
  { id: "shadow-of-the-colossus", title: "Shadow of the Colossus", year: 2005, genre: "Action-Adventure", platform: "PS2", dev: "Team Ico" },
  { id: "god-of-war", title: "God of War", year: 2005, genre: "Action", platform: "PS2", dev: "Santa Monica Studio" },
  { id: "okami", title: "Ōkami", year: 2006, genre: "Action-Adventure", platform: "PS2", dev: "Clover Studio" },
  { id: "wii-sports", title: "Wii Sports", year: 2006, genre: "Sports", platform: "Wii", dev: "Nintendo" },
  { id: "oblivion", title: "The Elder Scrolls IV: Oblivion", year: 2006, genre: "RPG", platform: "Xbox 360", dev: "Bethesda" },
  { id: "portal", title: "Portal", year: 2007, genre: "Puzzle", platform: "PC", dev: "Valve" },
  { id: "bioshock", title: "BioShock", year: 2007, genre: "Shooter", platform: "PC", dev: "Irrational Games" },
  { id: "super-mario-galaxy", title: "Super Mario Galaxy", year: 2007, genre: "Platformer", platform: "Wii", dev: "Nintendo" },
  { id: "mass-effect", title: "Mass Effect", year: 2007, genre: "RPG", platform: "Xbox 360", dev: "BioWare" },
  { id: "cod4-modern-warfare", title: "Call of Duty 4: Modern Warfare", year: 2007, genre: "Shooter", platform: "Multi", dev: "Infinity Ward" },
  { id: "team-fortress-2", title: "Team Fortress 2", year: 2007, genre: "Shooter", platform: "PC", dev: "Valve" },
  { id: "gta-iv", title: "Grand Theft Auto IV", year: 2008, genre: "Action", platform: "PS3", dev: "Rockstar North" },
  { id: "fallout-3", title: "Fallout 3", year: 2008, genre: "RPG", platform: "Multi", dev: "Bethesda" },
  { id: "uncharted-2", title: "Uncharted 2: Among Thieves", year: 2009, genre: "Action-Adventure", platform: "PS3", dev: "Naughty Dog" },
  { id: "batman-arkham-asylum", title: "Batman: Arkham Asylum", year: 2009, genre: "Action", platform: "PS3", dev: "Rocksteady" },
  { id: "demons-souls", title: "Demon's Souls", year: 2009, genre: "RPG", platform: "PS3", dev: "FromSoftware" },

  // 2010s
  { id: "mass-effect-2", title: "Mass Effect 2", year: 2010, genre: "RPG", platform: "Xbox 360", dev: "BioWare" },
  { id: "red-dead-redemption", title: "Red Dead Redemption", year: 2010, genre: "Action-Adventure", platform: "PS3", dev: "Rockstar San Diego" },
  { id: "super-meat-boy", title: "Super Meat Boy", year: 2010, genre: "Platformer", platform: "PC", dev: "Team Meat" },
  { id: "fallout-new-vegas", title: "Fallout: New Vegas", year: 2010, genre: "RPG", platform: "Multi", dev: "Obsidian" },
  { id: "civilization-v", title: "Civilization V", year: 2010, genre: "Strategy", platform: "PC", dev: "Firaxis" },
  { id: "minecraft", title: "Minecraft", year: 2011, genre: "Sandbox", platform: "PC", dev: "Mojang" },
  { id: "skyrim", title: "The Elder Scrolls V: Skyrim", year: 2011, genre: "RPG", platform: "PC", dev: "Bethesda" },
  { id: "portal-2", title: "Portal 2", year: 2011, genre: "Puzzle", platform: "PC", dev: "Valve" },
  { id: "dark-souls", title: "Dark Souls", year: 2011, genre: "RPG", platform: "PS3", dev: "FromSoftware" },
  { id: "journey", title: "Journey", year: 2012, genre: "Action-Adventure", platform: "PS3", dev: "thatgamecompany" },
  { id: "xcom-enemy-unknown", title: "XCOM: Enemy Unknown", year: 2012, genre: "Strategy", platform: "PC", dev: "Firaxis" },
  { id: "dishonored", title: "Dishonored", year: 2012, genre: "Action", platform: "PC", dev: "Arkane Studios" },
  { id: "ftl", title: "FTL: Faster Than Light", year: 2012, genre: "Roguelike", platform: "PC", dev: "Subset Games" },
  { id: "papers-please", title: "Papers, Please", year: 2013, genre: "Puzzle", platform: "PC", dev: "Lucas Pope" },
  { id: "the-last-of-us", title: "The Last of Us", year: 2013, genre: "Action-Adventure", platform: "PS3", dev: "Naughty Dog" },
  { id: "gta-v", title: "Grand Theft Auto V", year: 2013, genre: "Action", platform: "Multi", dev: "Rockstar North" },
  { id: "bloodborne", title: "Bloodborne", year: 2015, genre: "RPG", platform: "PS4", dev: "FromSoftware" },
  { id: "the-witcher-3", title: "The Witcher 3: Wild Hunt", year: 2015, genre: "RPG", platform: "PC", dev: "CD Projekt Red" },
  { id: "metal-gear-solid-v", title: "Metal Gear Solid V: The Phantom Pain", year: 2015, genre: "Action", platform: "Multi", dev: "Konami" },
  { id: "undertale", title: "Undertale", year: 2015, genre: "RPG", platform: "PC", dev: "Toby Fox" },
  { id: "rocket-league", title: "Rocket League", year: 2015, genre: "Sports", platform: "PC", dev: "Psyonix" },
  { id: "overwatch", title: "Overwatch", year: 2016, genre: "Shooter", platform: "PC", dev: "Blizzard" },
  { id: "doom-2016", title: "DOOM (2016)", year: 2016, genre: "Shooter", platform: "PC", dev: "id Software" },
  { id: "stardew-valley", title: "Stardew Valley", year: 2016, genre: "Simulation", platform: "PC", dev: "ConcernedApe" },
  { id: "zelda-breath-of-the-wild", title: "The Legend of Zelda: Breath of the Wild", year: 2017, genre: "Action-Adventure", platform: "Switch", dev: "Nintendo" },
  { id: "super-mario-odyssey", title: "Super Mario Odyssey", year: 2017, genre: "Platformer", platform: "Switch", dev: "Nintendo" },
  { id: "persona-5", title: "Persona 5", year: 2017, genre: "RPG", platform: "PS4", dev: "Atlus" },
  { id: "nier-automata", title: "NieR: Automata", year: 2017, genre: "RPG", platform: "PS4", dev: "PlatinumGames" },
  { id: "hollow-knight", title: "Hollow Knight", year: 2017, genre: "Platformer", platform: "PC", dev: "Team Cherry" },
  { id: "cuphead", title: "Cuphead", year: 2017, genre: "Platformer", platform: "PC", dev: "StudioMDHR" },
  { id: "dead-cells", title: "Dead Cells", year: 2017, genre: "Roguelike", platform: "PC", dev: "Motion Twin" },
  { id: "god-of-war-2018", title: "God of War", year: 2018, genre: "Action-Adventure", platform: "PS4", dev: "Santa Monica Studio" },
  { id: "red-dead-redemption-2", title: "Red Dead Redemption 2", year: 2018, genre: "Action-Adventure", platform: "PS4", dev: "Rockstar Games" },
  { id: "celeste", title: "Celeste", year: 2018, genre: "Platformer", platform: "PC", dev: "Maddy Makes Games" },
  { id: "sekiro", title: "Sekiro: Shadows Die Twice", year: 2019, genre: "Action", platform: "PC", dev: "FromSoftware" },
  { id: "disco-elysium", title: "Disco Elysium", year: 2019, genre: "RPG", platform: "PC", dev: "ZA/UM" },
  { id: "outer-wilds", title: "Outer Wilds", year: 2019, genre: "Action-Adventure", platform: "PC", dev: "Mobius Digital" },
  { id: "baba-is-you", title: "Baba Is You", year: 2019, genre: "Puzzle", platform: "PC", dev: "Hempuli" },
  { id: "slay-the-spire", title: "Slay the Spire", year: 2019, genre: "Roguelike", platform: "PC", dev: "Mega Crit" },

  // 2020s
  { id: "hades", title: "Hades", year: 2020, genre: "Roguelike", platform: "PC", dev: "Supergiant Games" },
  { id: "animal-crossing-new-horizons", title: "Animal Crossing: New Horizons", year: 2020, genre: "Simulation", platform: "Switch", dev: "Nintendo" },
  { id: "half-life-alyx", title: "Half-Life: Alyx", year: 2020, genre: "Shooter", platform: "PC", dev: "Valve" },
  { id: "it-takes-two", title: "It Takes Two", year: 2021, genre: "Action-Adventure", platform: "PC", dev: "Hazelight" },
  { id: "metroid-dread", title: "Metroid Dread", year: 2021, genre: "Action-Adventure", platform: "Switch", dev: "Nintendo" },
  { id: "forza-horizon-5", title: "Forza Horizon 5", year: 2021, genre: "Racing", platform: "Xbox Series", dev: "Playground Games" },
  { id: "inscryption", title: "Inscryption", year: 2021, genre: "Roguelike", platform: "PC", dev: "Daniel Mullins" },
  { id: "elden-ring", title: "Elden Ring", year: 2022, genre: "RPG", platform: "Multi", dev: "FromSoftware" },
  { id: "vampire-survivors", title: "Vampire Survivors", year: 2022, genre: "Roguelike", platform: "PC", dev: "poncle" },
  { id: "zelda-tears-of-the-kingdom", title: "The Legend of Zelda: Tears of the Kingdom", year: 2023, genre: "Action-Adventure", platform: "Switch", dev: "Nintendo" },
  { id: "baldurs-gate-3", title: "Baldur's Gate 3", year: 2023, genre: "RPG", platform: "PC", dev: "Larian Studios" },
  { id: "super-mario-bros-wonder", title: "Super Mario Bros. Wonder", year: 2023, genre: "Platformer", platform: "Switch", dev: "Nintendo" },
  { id: "astro-bot", title: "Astro Bot", year: 2024, genre: "Platformer", platform: "PS5", dev: "Team Asobi" },
  { id: "balatro", title: "Balatro", year: 2024, genre: "Roguelike", platform: "PC", dev: "LocalThunk" },
  { id: "metaphor-refantazio", title: "Metaphor: ReFantazio", year: 2024, genre: "RPG", platform: "Multi", dev: "Atlus" },
  { id: "animal-well", title: "Animal Well", year: 2024, genre: "Puzzle", platform: "PC", dev: "Billy Basso" },
  { id: "clair-obscur", title: "Clair Obscur: Expedition 33", year: 2025, genre: "RPG", platform: "Multi", dev: "Sandfall Interactive" },
  { id: "mario-kart-world", title: "Mario Kart World", year: 2025, genre: "Racing", platform: "Switch 2", dev: "Nintendo" },
];
